services:
  vite-react-template:
    build: .
    ports:
      - '5173:5173'
    volumes:
      - .:/app
    restart: 'always'
    stdin_open: true
    tty: true
    # env_file:
    #   - .env
    # healthcheck:
    #   test: ['CMD', 'wget', '-qO-', 'http://localhost:5173']
    #   interval: 30s
    #   timeout: 3s
    #   retries: 3
